version: '3.4'

services:
########################################################## stocks.api ###################################################################################
########################################################## mongo.db ##################################################################################
 # mongo.db:
  #  image: ${DOCKER_REGISTRY-}mongodb
  #  container_name: mongo.db
  #  mem_limit: 1536m
  #  mem_reservation: 128M
  #  cpus: 1.0
  #  ports:
  #     - 27018:27017
  #  build:
  #    context: .
  #    dockerfile: mongo.db/Dockerfile
  #  networks:
  #   - backend

########################################################## stocks.api ###################################################################################
  stocks.api:
    image: ${DOCKER_REGISTRY-}stocksapi
    build:
      context: .
      dockerfile: Stocks.Api/Dockerfile
    depends_on:
     - mongo.server
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SECRETPASSWORD
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
 
    ports:
      - "8095:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro
    networks:
     - backend
########################################################## networks #######################################################################################################
networks:
  backend:
    name: backend
    driver: bridge
    external: true

